/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import Models.ShowOrders;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mdala
 */
public class ShowOrdersUI extends javax.swing.JFrame {

    /**
     * Creates new form ShowOrdersUI
     */
    Connection con;
    public ShowOrdersUI() {
        initComponents();
        createConnection();
        displayToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Service", "Price", "Employee FIrst Name", "Employee Last Name", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowOrdersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowOrdersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowOrdersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowOrdersUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowOrdersUI().setVisible(true);
            }
        });
    }
    
    public void createConnection(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
             this.con = DriverManager.getConnection("jdbc:mysql://localhost:3306/drivingschool", "root", "sadath2010");
             System.out.println("connected");
            
        }catch (Exception ex){
            ex.getMessage();
        }
    }
    public ArrayList<ShowOrders> userList(){
        ArrayList<ShowOrders> userList = new ArrayList<>();
        try { 
            Statement stmt = con.createStatement();
            String query = "select c.fname as customer_fname,c.lname as customer_lname,s.service_description,s.price,e.fname as employee_fname,e.lname as employee_lname, o.order_date\n" +
"from orders o, services s, customer c, employee e\n" +
"where o.service_id = s.service_id AND o.customer_number = c.customer_number AND o.employee_id = e.employee_id";

            ResultSet rs = stmt.executeQuery(query);
            ShowOrders showOrders;
            while(rs.next()){
                showOrders = new ShowOrders(rs.getString("customer_fname"),rs.getString("customer_lname"),rs.getString("service_description"),rs.getInt("price"),rs.getString("employee_fname"),rs.getString("employee_lname"),rs.getDate("order_date"));
                userList.add(showOrders);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GrossEarningUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        return userList; 
    }
    
    public void displayToTable(){
        ArrayList<ShowOrders> list = userList();
        DefaultTableModel model =(DefaultTableModel) table.getModel();
        Object[] row = new Object[7];
        for(int i = 0; i< list.size(); i++){
           row[0] = list.get(i).getCustomerFName();
           row[1] = list.get(i).getCustomerLName();
           row[2] = list.get(i).getService();
           row[3] = list.get(i).getPrice();
           row[4] = list.get(i).getEmployeeFName();
           row[5] = list.get(i).getEmployeeLName();
           row[6] = list.get(i).getDate();
            model.addRow(row);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
