/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Models.GrossEarning;
import Models.VehicleUse;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mdala
 */
public class VehicleReportUI extends javax.swing.JFrame {

    /**
     * Creates new form VehicleReportUI
     */
    Connection con;
    public VehicleReportUI() {
        initComponents();
        createConnection();
        displayToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Make", "Model", "Color", "Miles", "Customer First Name", "Customer Last name", "Employee First Name", "Employee Last Name", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleReportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleReportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleReportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleReportUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleReportUI().setVisible(true);
            }
        });
    }
     public void createConnection(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
             this.con = DriverManager.getConnection("jdbc:mysql://localhost:3306/drivingschool", "root", "sadath2010");
             System.out.println("connected");
            
        }catch (Exception ex){
            ex.getMessage();
        }
    }
    public ArrayList<VehicleUse> userList(){
        ArrayList<VehicleUse> userList = new ArrayList<>();
        try { 
            Statement stmt = con.createStatement();
            String query = "select  v.make, v.model, v.color, v.miles, c.fname as customer_fname, c.lname as customer_lname, e.fname as employee_fname,e.lname as employee_lname,o.order_date\n" +
"from orders o, customer c, vehicle v, employee e\n" +
"where o.vehicle_id = v.vehicle_id AND o.customer_number = c.customer_number AND o.employee_id = e.employee_id";
            ResultSet rs = stmt.executeQuery(query);
            VehicleUse vh; 
            while(rs.next()){
                vh = new VehicleUse(rs.getString("make"),rs.getString("model"),rs.getString("color"),rs.getInt("miles"),rs.getString("customer_fname"),rs.getString("customer_lname"),rs.getString("employee_fname"),rs.getString("employee_lname"),rs.getDate("order_date"));
                userList.add(vh);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GrossEarningUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        return userList; 
    }
    
    public void displayToTable(){
        ArrayList<VehicleUse> list = userList();
        DefaultTableModel model =(DefaultTableModel) table.getModel();
        Object[] row = new Object[9];
        for(int i = 0; i< list.size(); i++){
            row[0] = list.get(i).getMake();
            row[1] = list.get(i).getModel();
            row[2] = list.get(i).getColr();
            row[3] = list.get(i).getMiles();
            row[4] = list.get(i).getCustomerFirstName();
            row[5] = list.get(i).getCustomerLastName();
            row[6] = list.get(i).getEmployeeFirstName();
            row[7] = list.get(i).getEmployeeLastName();
            row[8] = list.get(i).getDate();
            
            model.addRow(row);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
